services:
    ezplatform.core.command.user_purge:
        class: Tutei\GDPRBundle\Command\UserPurgeCommand
        arguments:
            - '@ezpublish.api.repository'
        tags:
            - { name: console.command }
    ezplatform.core.command.user_hide:
        class: Tutei\GDPRBundle\Command\HideUserContentCommand
        arguments:
            - '@ezpublish.api.repository'
        tags:
            - { name: console.command }
    ezplatform.core.command.user_export:
        class: Tutei\GDPRBundle\Command\UserExportCommand
        arguments:
            - '@ezpublish.api.repository'
        tags:
            - { name: console.command }