services:
    ezplatform.core.command.trash_purge:
        class: Tutei\GDPRBundle\Command\UserPurgeCommand
        arguments:
            - '@ezpublish.api.repository'
        tags:
            - { name: console.command }
